using System.Text;
using FluentMigrator;
using FluentMigrator.Expressions;
using FluentMigrator.Model;
using System.Data;
using FluentMigrator.Runner.Generators;
using Pondhawk.Persistence.Core.Introspection;
using Pondhawk.Persistence.Core.Models;
using Attribute = Pondhawk.Persistence.Core.Models.Attribute;
using Models_Attribute = Pondhawk.Persistence.Core.Models.Attribute;

namespace Pondhawk.Persistence.Core.Ddl;

public abstract class DdlGeneratorBase : IDdlGenerator
{
    protected abstract string ProviderName { get; }
    protected abstract IMigrationGenerator GetMigrationGenerator();
    protected abstract string GenerateEnumDdl(SchemaFileEnum enumDef);

    protected List<SchemaFileEnum> Enums { get; private set; } = [];

    protected SchemaFileEnum? FindEnum(string dataType)
    {
        return Enums.FirstOrDefault(e => string.Equals(e.Name, dataType, StringComparison.OrdinalIgnoreCase));
    }

    protected virtual string ResolveColumnType(Models_Attribute attr)
    {
        var e = FindEnum(attr.DataType);
        return e != null ? MapEnumColumnType(e) : DdlTypeMapper.MapType(ProviderName, attr.DataType);
    }

    protected virtual string MapEnumColumnType(SchemaFileEnum enumDef) =>
        DdlTypeMapper.MapType(ProviderName, "varchar(255)");

    protected virtual string GenerateEnumConstraints(Model model) => "";

    protected virtual string PostProcessCreateTable(string ddl, Model model) => ddl;

    protected virtual string ProcessDefaultValue(Models_Attribute attr) => attr.DefaultValue!;

    public string Generate(List<Model> models, List<SchemaFileEnum>? enums = null,
        string? projectName = null, string? description = null)
    {
        Enums = enums ?? [];

        var sb = new StringBuilder();
        var label = string.IsNullOrWhiteSpace(projectName) ? "pondhawk-mcp" : projectName;
        sb.AppendLine($"-- Generated by pondhawk-mcp for {label} on {DateTime.UtcNow:yyyy-MM-dd}");
        if (!string.IsNullOrWhiteSpace(description))
            sb.AppendLine($"-- {description}");
        sb.AppendLine();

        // 1. Enum types
        if (enums is not null)
        {
            foreach (var e in enums)
            {
                var enumDdl = GenerateEnumDdl(e);
                if (!string.IsNullOrEmpty(enumDdl))
                    sb.Append(enumDdl);
            }
        }

        // 2. Topological sort tables (exclude views — views are not emitted as DDL)
        var sorted = TopologicalSort(models.Where(m => !m.IsView).ToList());

        // 3. Get FluentMigrator generator
        var generator = GetMigrationGenerator();

        // 4. CREATE TABLE (without FKs)
        foreach (var model in sorted)
        {
            if (!string.IsNullOrEmpty(model.Note))
                sb.AppendLine($"-- {model.Note}");

            var expr = BuildCreateTableExpression(model);
            var ddl = generator.Generate(expr);

            // Inject column notes as inline SQL comments
            ddl = InjectColumnNotes(ddl, model);

            // Allow dialect-specific post-processing (e.g., SQLite inline CHECK constraints)
            ddl = PostProcessCreateTable(ddl, model);

            sb.AppendLine(ddl);
            sb.AppendLine();
        }

        // 5. CREATE INDEX (skip indexes that duplicate the primary key)
        foreach (var model in sorted)
        {
            var pkCols = model.PrimaryKey?.Columns;
            var wrote = false;
            foreach (var idx in model.Indexes)
            {
                if (pkCols is { Count: > 0 }
                    && idx.Columns.Count == pkCols.Count
                    && new HashSet<string>(idx.Columns, StringComparer.OrdinalIgnoreCase).SetEquals(pkCols))
                    continue;

                var expr = BuildCreateIndexExpression(model, idx);
                sb.AppendLine(generator.Generate(expr));
                wrote = true;
            }
            if (wrote)
                sb.AppendLine();
        }

        // 6. ALTER TABLE ADD CONSTRAINT FOREIGN KEY
        foreach (var model in sorted)
        {
            foreach (var fk in model.ForeignKeys)
            {
                var expr = BuildCreateForeignKeyExpression(model, fk);
                sb.AppendLine(generator.Generate(expr));
            }
            if (model.ForeignKeys.Count > 0)
                sb.AppendLine();
        }

        // 7. Enum CHECK constraints (dialect-specific)
        foreach (var model in sorted)
            sb.Append(GenerateEnumConstraints(model));

        return sb.ToString();
    }

    private CreateTableExpression BuildCreateTableExpression(Model model)
    {
        var expr = new CreateTableExpression
        {
            TableName = model.Name,
            SchemaName = model.Schema
        };

        // Determine PK name for the constraint
        string? pkName = null;
        if (model.PrimaryKey is not null && model.PrimaryKey.Columns.Count > 0)
        {
            pkName = !string.IsNullOrEmpty(model.PrimaryKey.Name)
                ? model.PrimaryKey.Name
                : $"PK_{model.Name}";
        }

        foreach (var attr in model.Attributes)
        {
            var col = new ColumnDefinition
            {
                Name = attr.Name,
                CustomType = ResolveColumnType(attr),
                IsNullable = attr.IsNullable,
                IsPrimaryKey = model.PrimaryKey?.Columns.Contains(attr.Name) ?? false,
                IsIdentity = attr.IsIdentity,
                PrimaryKeyName = (model.PrimaryKey?.Columns.Contains(attr.Name) ?? false) ? pkName : null
            };

            if (!string.IsNullOrEmpty(attr.DefaultValue) && !attr.IsIdentity)
                col.DefaultValue = RawSql.Insert(ProcessDefaultValue(attr));

            expr.Columns.Add(col);
        }

        return expr;
    }

    private CreateIndexExpression BuildCreateIndexExpression(Model model, IndexInfo idx)
    {
        var indexName = !string.IsNullOrEmpty(idx.Name)
            ? idx.Name
            : $"IX_{model.Name}_{string.Join("_", idx.Columns)}";

        var expr = new CreateIndexExpression
        {
            Index = new IndexDefinition
            {
                Name = indexName,
                TableName = model.Name,
                SchemaName = model.Schema,
                IsUnique = idx.IsUnique
            }
        };

        foreach (var colName in idx.Columns)
        {
            expr.Index.Columns.Add(new IndexColumnDefinition
            {
                Name = colName,
                Direction = Direction.Ascending
            });
        }

        return expr;
    }

    private CreateForeignKeyExpression BuildCreateForeignKeyExpression(Model model, ForeignKey fk)
    {
        var fkName = !string.IsNullOrEmpty(fk.Name)
            ? fk.Name
            : $"FK_{model.Name}_{fk.PrincipalTable}";

        var expr = new CreateForeignKeyExpression
        {
            ForeignKey = new ForeignKeyDefinition
            {
                Name = fkName,
                ForeignTable = model.Name,
                ForeignTableSchema = model.Schema,
                PrimaryTable = fk.PrincipalTable,
                PrimaryTableSchema = fk.PrincipalSchema,
                OnDelete = MapRule(fk.OnDelete),
                OnUpdate = MapRule(fk.OnUpdate)
            }
        };

        foreach (var col in fk.Columns)
            expr.ForeignKey.ForeignColumns.Add(col);
        foreach (var col in fk.PrincipalColumns)
            expr.ForeignKey.PrimaryColumns.Add(col);

        return expr;
    }

    private static Rule MapRule(string? action) => action switch
    {
        "Cascade" => Rule.Cascade,
        "SetNull" => Rule.SetNull,
        "SetDefault" => Rule.SetDefault,
        "Restrict" => Rule.None, // FM uses None for NO ACTION / RESTRICT
        "NoAction" => Rule.None,
        _ => Rule.None
    };

    /// <summary>
    /// Injects column notes as inline SQL comments into the generated DDL.
    /// Finds each column name in the DDL and appends the note after its definition.
    /// </summary>
    private static string InjectColumnNotes(string ddl, Model model)
    {
        var columnsWithNotes = model.Attributes.Where(a => !string.IsNullOrEmpty(a.Note)).ToList();
        if (columnsWithNotes.Count == 0)
            return ddl;

        foreach (var attr in columnsWithNotes)
        {
            // Find the column definition in the DDL and append the note
            // The note goes before the comma separator or closing paren
            var note = $" /* {attr.Note} */";

            // Strategy: find the column name (quoted) followed by its definition,
            // then insert the note at the end of that column's definition.
            // We look for the next comma or PRIMARY KEY keyword as the boundary.
            var namePatterns = new[]
            {
                $"[{attr.Name}]",       // SQL Server
                $"\"{attr.Name}\"",     // PostgreSQL, SQLite
                $"`{attr.Name}`"        // MySQL
            };

            foreach (var namePattern in namePatterns)
            {
                var nameIdx = ddl.IndexOf(namePattern, StringComparison.Ordinal);
                if (nameIdx < 0) continue;

                // Find the end of this column's definition (next comma or closing paren before PRIMARY KEY)
                var afterName = nameIdx + namePattern.Length;
                var commaIdx = -1;

                // Scan forward for the next comma or ");" that ends this column definition
                for (var i = afterName; i < ddl.Length; i++)
                {
                    if (ddl[i] == ',')
                    {
                        commaIdx = i;
                        break;
                    }

                    // Check if we hit PRIMARY KEY or end of columns
                    if (i + 11 < ddl.Length && ddl.Substring(i, 11) == "PRIMARY KEY")
                    {
                        // Back up to the comma before PRIMARY KEY
                        commaIdx = i;
                        // Find the preceding comma
                        for (var j = i - 1; j > afterName; j--)
                        {
                            if (ddl[j] == ',')
                            {
                                commaIdx = j;
                                break;
                            }
                        }
                        break;
                    }
                }

                if (commaIdx > afterName)
                {
                    ddl = ddl.Insert(commaIdx, note);
                    break;
                }
            }
        }

        return ddl;
    }

    /// <summary>
    /// Topological sort on FK dependencies. Tables with no outgoing FKs come first.
    /// Circular references are handled gracefully — the sort is best-effort.
    /// </summary>
    internal static List<Model> TopologicalSort(List<Model> models)
    {
        var modelMap = new Dictionary<string, Model>(StringComparer.OrdinalIgnoreCase);
        foreach (var m in models)
            modelMap[m.Name] = m;

        var visited = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var inStack = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var result = new List<Model>();

        foreach (var m in models)
            Visit(m.Name, modelMap, visited, inStack, result);

        return result;
    }

    private static void Visit(string name, Dictionary<string, Model> map,
        HashSet<string> visited, HashSet<string> inStack, List<Model> result)
    {
        if (visited.Contains(name))
            return;

        if (inStack.Contains(name))
            return; // Circular reference — break the cycle

        if (!map.TryGetValue(name, out var model))
            return;

        inStack.Add(name);

        // Visit dependencies first (tables we reference via FKs)
        foreach (var fk in model.ForeignKeys)
        {
            if (!string.Equals(fk.PrincipalTable, name, StringComparison.OrdinalIgnoreCase))
                Visit(fk.PrincipalTable, map, visited, inStack, result);
        }

        inStack.Remove(name);
        visited.Add(name);
        result.Add(model);
    }
}
