using System.Text.Json;
using Pondhawk.Generation.Configuration;
using Pondhawk.Generation.Models;
using Pondhawk.Generation.Rendering;
using Pondhawk.Generation.Mcp;
using Pondhawk.Generation.Mcp.Tools;
using Shouldly;

namespace Pondhawk.Generation.Mcp.Tests.Tools;

public class InitToolTests : IDisposable
{
    private readonly string _tempDir;

    public InitToolTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"pondhawk_init_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempDir))
            Directory.Delete(_tempDir, true);
    }

    private string Path_(params string[] parts)
        => System.IO.Path.Combine([_tempDir, .. parts]);

    [Fact]
    public void Init_CreatesAllExpectedFiles()
    {
        var result = InitTool.Execute(new ServerContext(_tempDir));
        var json = JsonDocument.Parse(result);

        json.RootElement.GetProperty("FilesCreated").GetArrayLength().ShouldBe(9);
        File.Exists(Path_("pondhawk.project.json")).ShouldBeTrue();
        File.Exists(Path_("pondhawk.project.schema.json")).ShouldBeTrue();
        File.Exists(Path_("model.json")).ShouldBeTrue();
        File.Exists(Path_("model.schema.json")).ShouldBeTrue();
        File.Exists(Path_("AGENTS.md")).ShouldBeTrue();
        File.Exists(Path_(".env")).ShouldBeTrue();
        File.Exists(Path_("templates", "reference.liquid")).ShouldBeTrue();
        File.Exists(Path_("templates", "notes.liquid")).ShouldBeTrue();
    }

    [Fact]
    public void Init_ThrowsError_WhenConfigExists()
    {
        File.WriteAllText(Path_("pondhawk.project.json"), "{}");

        Should.Throw<InvalidOperationException>(() => InitTool.Execute(new ServerContext(_tempDir)))
            .Message.ShouldContain("already exists");
    }

    [Fact]
    public void Init_AppliesProjectNameParameter()
    {
        InitTool.Execute(new ServerContext(_tempDir), projectName: "Catalog");

        ProjectConfigurationLoader.Load(Path_("pondhawk.project.json")).ProjectName.ShouldBe("Catalog");
        ModelFileLoader.Load(Path_("model.json")).Name.ShouldBe("Catalog");
    }

    [Fact]
    public void Init_AppliesOutputDirParameter()
    {
        InitTool.Execute(new ServerContext(_tempDir), outputDir: "gen");

        ProjectConfigurationLoader.Load(Path_("pondhawk.project.json")).OutputDir.ShouldBe("gen");
    }

    [Fact]
    public void Init_GeneratedTemplatesAreValidLiquid()
    {
        InitTool.Execute(new ServerContext(_tempDir));
        var engine = new TemplateEngine();

        foreach (var name in new[] { "reference.liquid", "notes.liquid" })
        {
            var source = File.ReadAllText(Path_("templates", name));
            engine.TryParse(source, out _, out var error).ShouldBeTrue($"{name}: {error}");
        }
    }

    [Fact]
    public void Init_ScaffoldedProjectValidatesCleanly()
    {
        // The scaffold is the first thing anyone runs, so it must not emit its own warnings.
        var ctx = new ServerContext(_tempDir);
        InitTool.Execute(ctx);

        var rawJson = File.ReadAllText(Path_("pondhawk.project.json"));
        var config = ProjectConfigurationLoader.Deserialize(rawJson);
        var result = ConfigurationValidator.Validate(rawJson, config, _tempDir);

        result.Errors.ShouldBeEmpty();
        result.Warnings.ShouldBeEmpty();
    }

    [Fact]
    public void Init_ScaffoldedProjectGenerates()
    {
        var ctx = new ServerContext(_tempDir);
        InitTool.Execute(ctx);

        GenerateTool.Execute(ctx);

        // Pinned exactly: Liquid whitespace control is easy to get subtly wrong, and stray
        // blank lines in the very first file a user sees are the scaffold's worst advert.
        File.ReadAllText(Path_("generated", "Example.generated.md")).ReplaceLineEndings("\n").ShouldBe(
            """
            <!-- Generated by pondhawk. Rewritten on every run: edit the template, not this file. -->

            # Example

            A placeholder node. Replace it, and its Kinds, with your own.

            | Field | Required | Description |
            | ----- | -------- | ----------- |
            | Id | yes | Unique identifier |
            | Title | yes | Display name |
            | Notes | no | Free text |

            Maintained by MyTeam.

            """.ReplaceLineEndings("\n"));
    }

    [Fact]
    public void Init_ScaffoldedStubIsCleanToo()
    {
        var ctx = new ServerContext(_tempDir);
        InitTool.Execute(ctx);
        GenerateTool.Execute(ctx);

        File.ReadAllText(Path_("generated", "Example.notes.md")).ReplaceLineEndings("\n").ShouldBe(
            """
            # Example — notes

            Hand-written notes about Example. Created once and never
            overwritten: this file is yours.

            """.ReplaceLineEndings("\n"));
    }

    [Fact]
    public void Init_StarterModelMatchesItsSchema()
    {
        InitTool.Execute(new ServerContext(_tempDir));

        ModelFileSchema.Validate(File.ReadAllText(Path_("model.json"))).ShouldBeEmpty();
    }

    [Fact]
    public void Init_ConfigIncludesLoggingSectionDisabled()
    {
        InitTool.Execute(new ServerContext(_tempDir));

        var config = File.ReadAllText(Path_("pondhawk.project.json"));
        config.ShouldContain("Logging");
        config.ShouldContain("\"Enabled\": false");
    }

    [Fact]
    public void Init_DoesNotOverwriteAnExistingModel()
    {
        File.WriteAllText(Path_("model.json"), """{ "Name": "Mine", "Nodes": [] }""");
        InitTool.Execute(new ServerContext(_tempDir));

        ModelFileLoader.Load(Path_("model.json")).Name.ShouldBe("Mine");
    }

    [Fact]
    public void Init_ScaffoldsNothingTiedToATargetLanguage()
    {
        // The scaffold is a demonstration of the mechanics, not a starting point for real
        // templates. Anything language-shaped in here would be a starter template pack by
        // another name — frozen at build time and inviting edits rather than replacement.
        InitTool.Execute(new ServerContext(_tempDir));

        var scaffolded = Directory
            .EnumerateFiles(_tempDir, "*", SearchOption.AllDirectories)
            .Where(f => !f.EndsWith("AGENTS.md") && !f.Contains(".schema.json"))
            .Select(File.ReadAllText)
            .ToList();

        foreach (var giveaway in new[] { "namespace", "partial class", "get; set;", ".cs", "public " })
            scaffolded.ShouldNotContain(c => c.Contains(giveaway, StringComparison.OrdinalIgnoreCase), giveaway);
    }

    [Fact]
    public void Init_ScaffoldedProjectGeneratesCleanlyAndDemonstratesBothModes()
    {
        InitTool.Execute(new ServerContext(_tempDir), outputDir: "generated");

        var first = JsonDocument.Parse(GenerateTool.Execute(new ServerContext(_tempDir))).RootElement;
        first.GetProperty("Success").GetBoolean().ShouldBeTrue();
        first.GetProperty("Created").GetInt32().ShouldBe(2);

        // Running twice is the clearest demonstration of what Mode does.
        var second = JsonDocument.Parse(GenerateTool.Execute(new ServerContext(_tempDir))).RootElement;
        second.GetProperty("Unchanged").GetInt32().ShouldBe(1);
        second.GetProperty("Skipped").GetInt32().ShouldBe(1);
    }

}
