using Pondhawk.Persistence.Core.Ddl;
using Pondhawk.Persistence.Core.Introspection;
using Pondhawk.Persistence.Core.Models;
using Shouldly;
using Attribute = Pondhawk.Persistence.Core.Models.Attribute;

namespace Pondhawk.Persistence.Core.Tests.Ddl;

public class SqliteDdlGeneratorTests
{
    private readonly IDdlGenerator _generator = DdlGeneratorFactory.Create("sqlite");

    [Fact]
    public void Autoincrement_InlinePrimaryKey()
    {
        var model = new Model
        {
            Name = "Users",
            Attributes = [new Attribute { Name = "Id", DataType = "int", IsPrimaryKey = true, IsIdentity = true }],
            PrimaryKey = new PrimaryKeyInfo { Columns = ["Id"] }
        };
        var ddl = _generator.Generate([model]);
        ddl.ShouldContain("PRIMARY KEY AUTOINCREMENT");
    }

    [Fact]
    public void DoubleQuoteIdentifiers()
    {
        var model = new Model
        {
            Name = "Users",
            Attributes = [new Attribute { Name = "Id", DataType = "int" }]
        };
        var ddl = _generator.Generate([model]);
        ddl.ShouldContain("\"Users\"");
        ddl.ShouldContain("\"Id\"");
    }

    [Fact]
    public void EnumCheckComment()
    {
        var enums = new List<SchemaFileEnum>
        {
            new() { Name = "Role", Values = [new() { Name = "Admin" }, new() { Name = "User" }] }
        };
        var ddl = _generator.Generate([], enums);
        ddl.ShouldContain("Enum: Role");
    }

    [Fact]
    public void EnumCheckConstraint()
    {
        var enums = new List<SchemaFileEnum>
        {
            new() { Name = "Role", Values = [new() { Name = "Admin" }, new() { Name = "User" }] }
        };
        var model = new Model
        {
            Name = "Users",
            Attributes =
            [
                new Attribute { Name = "Id", DataType = "int", IsPrimaryKey = true },
                new Attribute { Name = "UserRole", DataType = "Role" }
            ],
            PrimaryKey = new PrimaryKeyInfo { Columns = ["Id"] }
        };
        var ddl = _generator.Generate([model], enums);
        ddl.ShouldContain("CHECK (\"UserRole\" IN ('Admin', 'User'))");
        // Enum column should be mapped to TEXT
        ddl.ShouldContain("\"UserRole\" TEXT");
    }

    [Fact]
    public void TypeAffinity()
    {
        var model = new Model
        {
            Name = "Test",
            Attributes =
            [
                new Attribute { Name = "Col1", DataType = "int" },
                new Attribute { Name = "Col2", DataType = "varchar(255)" },
                new Attribute { Name = "Col3", DataType = "boolean" },
                new Attribute { Name = "Col4", DataType = "decimal" },
                new Attribute { Name = "Col5", DataType = "binary" }
            ]
        };
        var ddl = _generator.Generate([model]);
        ddl.ShouldContain("INTEGER");
        ddl.ShouldContain("TEXT");
        ddl.ShouldContain("REAL");
        ddl.ShouldContain("BLOB");
    }

    [Fact]
    public void CompositePrimaryKey()
    {
        var model = new Model
        {
            Name = "OrderItems",
            Attributes =
            [
                new Attribute { Name = "OrderId", DataType = "int", IsPrimaryKey = true },
                new Attribute { Name = "ProductId", DataType = "int", IsPrimaryKey = true }
            ],
            PrimaryKey = new PrimaryKeyInfo { Columns = ["OrderId", "ProductId"] }
        };
        var ddl = _generator.Generate([model]);
        ddl.ShouldContain("PRIMARY KEY (\"OrderId\", \"ProductId\")");
        ddl.ShouldNotContain("AUTOINCREMENT");
    }

    [Fact]
    public void EmptySchema_ProducesValidDdl()
    {
        var ddl = _generator.Generate([]);
        ddl.ShouldContain("Generated by pondhawk-mcp for pondhawk-mcp");
    }
}
